### ISSUE TITLE
Add "humidity_value" and "temp_current" code for temperature sensor 

### ISSUE THREAD

**Issue by stefg73** [Xenomes/Domoticz-TinyTUYA-Plugin#27] opened 2023-02-22 11:04 UTC
Hi,

please add this code to plugin.py because some temp sensor device use this code both in Stantard and DP mode.

Thanks

**Comment by Xenomes** [comment] 2023-02-22 19:49
Duplicate of #24

**Closed as completed by Xenomes** 2023-02-22 19:49 UTC
